### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/lxqt-organizer#27] opened 2020-07-13 19:14 UTC
![](https://saintmike.com/wp-content/uploads/AA1.jpg)
LXQt is not an anonymous club for hardcoded path designers. Many systems are not okay with keeping configs in the path of a binary or a current path. It would be _much better_ to store it somewhere in a home directory.
https://github.com/lxqt/organizer/blob/4a8484706ea83f863c8219f12df616d05b40d5b3/src/mainwindow.cpp#L2322
I'm also not a fan of storing settings in xml. There's `QSettings` class exactly for that. I suppose there are also many other ways to do it properly. Using DOM parser seems to be a huge overhead.
<s> P. S. I'm becoming more and more toxic here as the time goes by. This repo seems to be a cool inspiration for that... </s>

**Comment by tsujan** [comment] 2020-07-13 19:22
@shlyakpavel 
IMO, Organizer needs lots of changes before becoming congruent with LXQt. It can be seen as a work-in-progress.

Yes, `QSettings` should be used to save and restore settings.

**Comment by ghost** [comment] 2020-07-29 14:01
The latest code uses QSettings

**Comment by tsujan** [comment] 2020-07-29 15:00
@crispinalan 
Again, you added commits without making any PR or without taking a look at others' works (https://github.com/lxqt/organizer/pull/28). This isn't how we work in LXQt and I don't think any team work is possible in this way. It also discourages others from contributing to -- or even caring about -- Organizer.

If you want Organizer to be developed only by you -- which is understandable -- then you should make a repository in your GitHub page and we should remove it from here.

@luis-pereira, @jubalh, should we do it? If this continues, Organizer could never be an LXQt app.

**Comment by luis-pereira** [comment] 2020-07-29 15:40
> @crispinalan
> Again, you added commits without making any PR or without taking a look at others' works (#28). This isn't how we work in LXQt and I don't think any team work is possible in this way. It also discourages others from contributing to -- or even caring about -- Organizer.

I agree with every word.

> If you want Organizer to be developed only by you -- which is understandable -- then you should make a repository in your GitHub page and we should remove it from here.

If a developer continuously doesn't follow the LXQt development methodology, moving it to a personal page it's the best action for both the developer and the LXQt team.

> @luis-pereira, @jubalh, should we do it? If this continues, Organizer could never be an LXQt app.

I don't like it, but, if the situation doesn't improve it's the right thing to do.

**Comment by ghost** [comment] 2020-07-29 21:13
I pulled from the master branch before removing my custom translation system which was the issue raised by members and so all other changes and branches should remain unchanged. This raw code base on the master branch will allow the LXQt community to use core code  to add any further features required. I will not add any further updates to the LXQt Organizer code base which I developed for the LXQt project now that the two areas of concern have been addressed (QSettings and the translation system). Re "Organizer could never be an LXQt app"  I fully understand if you feel that organizer should not  be an LXQt app and in this case I suggest that you remove it.

**Comment by tsujan** [comment] 2020-07-29 21:51
> I pulled from the master branch before removing my custom translation system...

No one was in doubt about what you did -- everyone could see the changes -- and it wasn't the first time you did it. The problem is about *how* you do it.

> Re "Organizer could never be an LXQt app" I fully understand if you feel...

Please don't pull a sentence out of its real context and interpret it arbitrarily. The full sentence was, "*If this continues*, Organizer could never be an LXQt app". That's a practical matter and isn't related to anyone's "feelings".

Is it so hard to take a look at team projects on GitHub (in contrast to personal projects) to see how they're being developed?

**Comment by ghost** [comment] 2020-07-29 22:19
I made the core code changes for the LXQt community in light of comments such as "LXQt is not an anonymous club for hardcoded path designers", pictures of "Alcoholics Anonymous" and titles such as "Translation hell". Please remove the Organizer project from LXQt as the more I think about it I am not sure it is a natural fit for a desktop project. I have cloned it to my github page and so there are no problems of removing it immediately. I only developed the project when I was asked Alf Gaida.

**Comment by tsujan** [comment] 2020-07-30 00:04
I'm very sorry if you feel insulted by titles or attached images of some comments -- I think the commenters were honest, not rude -- and really hope that you rethink your decision.

The only thing that was asked from you was this: PR → Review → Merge (probably), instead of directly pushing to the master branch. Everyone does so here, even the founder of LXDE/LXQt, PCMan.

**Comment by ghost** [comment] 2020-07-30 06:47
Yes I should have made a code branch with the removal of the custom xml translation (translation hell issue #24)  system rather than remove it directly from the master branch. This would have allowed the changes to be reviewed as you say (my mistake).  I explained the reason why I originally developed the xml translation system this way in issue #24 at the time of writing the code. However, I still feel the project is not a natural fit to the LXQt desktop project and so please remove it and I will develop the code independently (as you suggested) and given other comments such as “Currently, there is no code style and formatting of the code is not really good (Suggestion - Use clang-format #29)”. Good luck with the LXQt project.

**Comment by Waqar144** [comment] 2020-07-30 19:44
>  “Currently, there is no code style and formatting of the code is not really good (Suggestion - Use clang-format #29)”

My intention was to improve this project, and I have been constantly trying to contribute and become a part of LXQt through this project because i felt like it needed help. My intention was never to insult or offend you. I apologize if the use of my language made you feel that way. I hope you keep this project here, it could definitely be a part of LXQt. :)

**Comment by jubalh** [comment] 2020-07-30 19:45
> @luis-pereira, @jubalh, should we do it? If this continues, Organizer could never be an LXQt app.

organizer has been problematic since some time indeed.

>  and given other comments such as “Currently, there is no code style and formatting of the code is not really good (Suggestion - Use clang-format #29

It indeed is a good suggestion to use clang format. Many projects do it. It is by no means an insult if someone suggests that the formatting is not consistent and a formatter should be used.

@crispinalan I assume you develop this project because you enjoy it. This is good. But when working in a team more things have to be considered.
I appreciate your efforts, but also see the problems.

How do you feel about continueing to develop organizer under LXQt, but withou access to the master branch. This way you can "force yourself" to use PRs. And while doing PRs the rest of the team will review. Like this the code quality/style and probably everybody learns something from the reviews.

I think it would be a win win.

Let us know what you think. I understand that at this point you might feel attacked from the comments you got. But I don't think anything was meant in a destructive way. People just wanted to improve something and felt like you repeatedly ignored the advice.

**Comment by jubalh** [comment] 2020-07-30 19:48
BTW I also find the "Alcoholics Anonymous" picture out of place and slightly offensive..

**Comment by shlyakpavel** [comment] 2020-07-31 18:32
> BTW I also find the "Alcoholics Anonymous" picture out of place and slightly offensive..

I'm really sorry if is looks offensive. This is just the kind of humour I have. 
![image](https://user-images.githubusercontent.com/19782228/89065904-301c0b00-d375-11ea-89a8-b397830fd3dd.png)

**Comment by ghost** [comment] 2020-08-01 12:47
It is noting to do with being insulted by comments or attached images but apologies again for not creating a branch when I removed the  “translation hell #24” working translation code from the master branch which did not  use the QTranslator standardised (tr hooks) approach. I can see how this would upset other developers now it is not just me developing the project which is what was happening in the very early stages. My motives were genuine in that I wanted a clean core base code on the master branch for others to branch so as to develop a standardised translation system.  However, I just feel that organizer has become a distraction from the overall LXQt project and so its removal will allow the team to focus on core aspects of the desktop. I do fully understand the thinking that it should never have been an LXQt app.  It is a good time to remove the project as the code is still in its infancy. The sort of changes that I have been looking into (CalDAV, CardDAV, dbus session messages, calendar code changes )  will require significant code restructuring which I can only see will cause major grief to the LXQt team. Regarding “If you want Organizer to be developed only by you -- which is understandable -- then you should make a repository in your GitHub page and we should remove it from here”.  Please remove the project immediately from the LXQt repository as I have code backups.  As I said good luck with the LXQt desktop.

**Comment by tsujan** [comment] 2022-05-05 06:17
Will be archived.

**Closed as completed by tsujan** 2022-05-05 06:17 UTC
